
name: Documentation
description: Something needs to be explained…
title: Documentation
labels: 
  - docs
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        On the [tutorials site](https://awkward-array.org/)?

        In the [Python docstrings](https://awkward-array.readthedocs.io/)?

        In the [C++ doxygen API](https://awkward-array.readthedocs.io/en/latest/_static/index.html)?

        What, specifically, needs more explanation?
  - type: dropdown
    id: layer
    attributes:
      label: What
      description: What part of Awkward Array needs documenting?
      default: Python API
      options:
        - Tutorials
        - Python API
        - C++ API
        - Other
    validations:
      required: true
 
  - type: textarea
    id: what
    attributes:
      label: What Needs Documentation
      description: Please describe what part of the Awkward API or usage you would like to see explained.
      placeholder: Tell us what needs documenting!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
